### ISSUE TITLE
Unsupported parameters for (ansible.builtin.user) module: password_expire_max 

### ISSUE THREAD

**Issue by dgowan777** [RedHatOfficial/ansible-role-rhel9-stig#1]
Dear ansible-role-rhel9-stig team,

You ROCK!  Thank you for this awesome role.  

I have experienced a failure on the following task: "Change the maximum time period between password changes".  What version of Ansible supports "password_expire_max"?  Ansible version 2.9 doesn't.  

Sample error message:

failed: [r9test01.gowan.tech] (item=root) => {"ansible_loop_var": "item", "changed": false, "item": "root", "msg": "Unsupported parameters for (ansible.builtin.user) module: password_expire_max Supported parameters include: append, authorization, comment, create_home, expires, force, generate_ssh_key, group, groups, hidden, home, local, login_class, move_home, name, non_unique, password, password_lock, profile, remove, role, seuser, shell, skeleton, ssh_key_bits, ssh_key_comment, ssh_key_file, ssh_key_passphrase, ssh_key_type, state, system, uid, update_password"}

Here is my Ansible info:

ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/darin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jan 14 2022, 11:04:20) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]

Typical work-around is to enable "ignore_errors" for this task.

Thank you.

Darin Gowan

**Comment by dgowan777** [comment]
I just found that "password_expire_max" was added in Ansible 2.11.

**Comment by dmc5179** [comment]
Issues should be reported here: https://github.com/ComplianceAsCode/content
