### ISSUE TITLE
Files in the 'pam' package have been altered, so the authselect configuration won't be forced

### ISSUE THREAD

**Issue by dgowan777** [RedHatOfficial/ansible-role-rhel9-stig#2]
Summary:
The RHEL 9 draft stig role was executed on a fresh install of RHEL 9.1.  The last three tasks executed are listed.  

The following was encountered during the execution of this role:

TASK [ansible-role-rhel9-stig-main : Select authselect profile] *******************************************************
fatal: [r9test100-84]: FAILED! => {"changed": true, "cmd": ["authselect", "select", "sssd"], "delta": "0:00:00.052065", "end": "2022-12-19 12:03:17.070120", "msg": "non-zero return code", "rc": 4, "start": "2022-12-19 12:03:17.018055", "stderr": "[error] File [/etc/pam.d/system-auth] exists but it needs to be overwritten!\n[error] File [/etc/pam.d/password-auth] exists but it needs to be overwritten!\n[error] File [/etc/pam.d/fingerprint-auth] exists but it needs to be overwritten!\n[error] File [/etc/pam.d/smartcard-auth] exists but it needs to be overwritten!\n[error] File [/etc/pam.d/postlogin] exists but it needs to be overwritten!\n[error] File [/etc/nsswitch.conf] exists but it needs to be overwritten!\n[error] File that needs to be overwritten was found\n[error] Refusing to activate profile unless this file is removed or overwrite is requested.\n\nSome unexpected changes to the configuration were detected.\nUse --force parameter if you want to overwrite these changes.", "stderr_lines": ["[error] File [/etc/pam.d/system-auth] exists but it needs to be overwritten!", "[error] File [/etc/pam.d/password-auth] exists but it needs to be overwritten!", "[error] File [/etc/pam.d/fingerprint-auth] exists but it needs to be overwritten!", "[error] File [/etc/pam.d/smartcard-auth] exists but it needs to be overwritten!", "[error] File [/etc/pam.d/postlogin] exists but it needs to be overwritten!", "[error] File [/etc/nsswitch.conf] exists but it needs to be overwritten!", "[error] File that needs to be overwritten was found", "[error] Refusing to activate profile unless this file is removed or overwrite is requested.", "", "Some unexpected changes to the configuration were detected.", "Use --force parameter if you want to overwrite these changes."], "stdout": "", "stdout_lines": []}
...ignoring

TASK [ansible-role-rhel9-stig-main : Verify if PAM has been altered] **************************************************
fatal: [r9test100-84]: FAILED! => {"changed": true, "cmd": ["rpm", "-qV", "pam"], "delta": "0:00:00.999445", "end": "2022-12-19 12:03:20.646329", "msg": "non-zero return code", "rc": 1, "start": "2022-12-19 12:03:19.646884", "stderr": "", "stderr_lines": [], "stdout": "S.5....T.  c /etc/security/faillock.conf", "stdout_lines": ["S.5....T.  c /etc/security/faillock.conf"]}
...ignoring

TASK [ansible-role-rhel9-stig-main : Informative message based on the authselect integrity check] *********************
fatal: [r9test100-84]: FAILED! => {
    "assertion": "result_altered_authselect is success",
    "changed": false,
    "evaluated_to": false,
    "msg": [
        "Files in the 'pam' package have been altered, so the authselect configuration won't be forced."
    ]
}

PLAY RECAP ************************************************************************************************************
r9test100-84               : ok=141  changed=41   unreachable=0    failed=1    skipped=23   rescued=0    ignored=2

Ansible info:
[gowanda@ceis-rhwks03 stig]$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gowanda/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Jan 14 2022, 11:04:20) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]

**Comment by dmc5179** [comment]
Issues should be reported here: https://github.com/ComplianceAsCode/content
