### ISSUE TITLE
Update for STIG

### ISSUE THREAD

**Issue by tredeske** [RedHatOfficial/ansible-role-rhel9-stig#3]
It looks like the actual STIG is now available: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.7.1_rhel9_oracle-linux9_x86_64_bundle.zip

When should we expect an update of these roles?

**Comment by dmc5179** [comment]
Latest version, 0.1.71, has been pushed to ansible galaxy
