### ISSUE TITLE
tmux case statement missing opening (

### ISSUE THREAD

**Issue by davewujcik** [RedHatOfficial/ansible-role-rhel9-stig#5]
in tasks/main.yml there are several instances of:
.*case "$name" in sshd|login) exec tmux ;; esac.*

This should be:
.*case "$name" in (sshd|login) exec tmux ;; esac.*
with the opening ( in front of sshd

This is on lines: 
https://github.com/RedHatOfficial/ansible-role-rhel9-stig/blob/b6253213e587758c70dc544f838c530647cca443/tasks/main.yml#L12995C15-L12995C64
https://github.com/RedHatOfficial/ansible-role-rhel9-stig/blob/b6253213e587758c70dc544f838c530647cca443/tasks/main.yml#L13019
https://github.com/RedHatOfficial/ansible-role-rhel9-stig/blob/b6253213e587758c70dc544f838c530647cca443/tasks/main.yml#L13019

Thanks,
-- dwujcik@redhat.com

**Comment by dmc5179** [comment]
Issues should be reported here: https://github.com/ComplianceAsCode/content
